version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    ports:
    - 45433:5432
    environment:
      POSTGRES_USER: creator_suite
      POSTGRES_PASSWORD: iehohp6iep5eez5fai3eechohdieQaas
      POSTGRES_DB: creator_suite_dev
    volumes:
      - creator_suite_db:/var/lib/postgresql/data
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_host
    volumes:
      - ./export:/export
      - ./ipfs_data:/data/ipfs
    ports:
      - '4001:4001'
      - '4001:4001/udp'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:5001:5001'
volumes:
  creator_suite_db: {}