version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_service
    hostname: postgres_service
    ports:
      - 45433:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - creator_suite_db:/var/lib/postgresql/data
  frontend:
    image: ghcr.io/nextdotid/creator_suite_frontend:latest
    container_name: frontend
    hostname: frontend
    build:
      dockerfile: './Dockerfile'
      context: './filebrowser'
    depends_on:
      - postgres
      - server
    ports:
      - "80:80"
  server:
    image: ghcr.io/nextdotid/creator_suite_server:latest
    container_name: creator-suite-server
    build:
      dockerfile: './Dockerfile'
      context: '.'
    hostname: backend
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TX_ACCOUNT: ${TX_ACCOUNT}
      RPC_SERVER_ON_CHAIN: ${RPC_SERVER_ON_CHAIN}
      CHAIN_ID: ${CHAIN_ID}
    volumes:
      - ~/storage:/storage
volumes:
  creator_suite_db: {}
