version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_service
    hostname: postgres_service
    ports:
      - 45433:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - creator_suite_db:/var/lib/postgresql/data
#  frontend:
#    image: ghcr.io/nextdotid/creator_suite_frontend_v2:latest
#    container_name: creator-suite-frontend
#    ports:
#      - "3001:3000"
#    environment:
#      NODE_ENV: development
  server:
    image: ghcr.io/nextdotid/creator_suite_server:latest
    container_name: creator-suite-server
    build:
      dockerfile: './Dockerfile'
      context: '.'
    hostname: backend
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      RPC_SERVER_ON_CHAIN: ${RPC_SERVER_ON_CHAIN}
    volumes:
      - ~/storage:/storage
volumes:
  creator_suite_db: {}
