[db]
host = "localhost"
port = 45433
user = "creator_suite"
password = ""
db_name = "creator_suite_dev"
tz = "UTC"

[chain]
rpc_server = "http://127.0.0.1:8545"
id = "5777"
tx_acc = ""
subscription_contract_address = "0xDCD4BBD2D16895604238e6D91BE49E9367aDF0c5"
gas_limit = 3000000
gas_price = 1000000