FORMAT: 1A
HOST: https://xxx

# CreatorSuite

CreatorSuite Service provides create and get api to distribute content asset for both creators and buyers.

## Create Content Asset [/create]

### Create a Content Asset [post]

 + Attributes (object)
    + managed_contract (string, required) - the contract that received the tokens
    + network (string, required) - interact network.
    + payment_token_address (string, required) - which token and how much it cost to unlock the content
    + payment_token_amount (string, required) - same as above
    + encryption_type (string, required) - encryption_type=1 symmetric encryption option, encryption_type=2 asymmetric encryption
    + password (string, optional) - depends on encryption_type. If encryption_type=1, use it encryption/decryption the content; if encryption_type=2, keep it empty.
    + file_extension (string, required) - record the file extension for decryption process

+ Request (application/json)

        {
            "managed_contract": "0x3A6c014579583c5D412A9F3914a67C0885dB90c0",
            "network":"mumbai",
            "payment_token_address": "0x9801ca34B280b60292692E3fD00599f0Fbb8d6b2",
            "payment_token_amount": "5" ,
            "password": "1234567890qwertq",
            "encryption_type":1,
            "file_extension":"jpg"
        }


+ Response 200 (application/json)

    {}

## Get a Specific Asset [/get-content]
### get a content asset [get]

After paying for a specific content asset, the buyer can call the get-content api to get the encrypted content asset

+ Parameters
    + public_key(string) - the public key of the account that make the payment of content asset
    + content_id(number) - the content asset ID

+ Response 200 (application/json)

    + Body

        {
            "encrypted_password": "",
            "encrypted_result": "",
            "encryption_type": 1, //encryption_type=1 symmetric encryption option, encryption_type=2 asymmetric encryption
            "file_extension": "jpg"
        }


