name: Build server container

on:
  push:
    tags:
      - "release-server/**"

jobs:
  build-server-image:
    if: github.repository == 'nextdotid/creator_suite'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}_server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to docker.io registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GHCR registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-build-${{ github.sha }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
            docker.io/${{ env.IMAGE_NAME }}
      - name: Get version
        env:
          BRANCH: ${{ github.ref_name }}
        id: version
        run: echo "tagname=${BRANCH##*/}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: '.'
          push: true
          file: Dockerfile
          tags: |
            ghcr.io/nextdotid/creator_suite_server:${{ steps.version.outputs.tagname}}
            ghcr.io/nextdotid/creator_suite_server:latest
            docker.io/nextdotid/creator_suite_server:${{ steps.version.outputs.tagname}}
            docker.io/nextdotid/creator_suite_server:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
